### ISSUE TITLE
Multiple Issue Filters in Rest API

### ISSUE THREAD

**Issue by alexeyOnGitHub** [taskadapter/redmine-java-api#12]
1. Using HashMap, create a subject filter (e.g.):
   ?set_filter=1&f[]=subject&op[subject]=~&v[subject][]=Facebook

   Map<String, String> query = new HashMap<String, String>();
   query.put("set_filter", "1");
   query.put("f[]", "subject");
   query.put("op[subject]", "~");
   query.put("v[subject][]", "Facebook");

2. Using same HashMap, add an additional assignee filter (e.g.):
   f[]=assigned_to_id&op[assigned_to_id]=%3D&v[assigned_to_id][]=41

   query.put("f[]", "assigned_to_id");
   query.put("op[assigned_to_id]", "=");
   query.put("v[assigned_to_id][]", "41");

3. Call RedmineManager.getIssues(Map) with the query HashMap.

Expected output should be a URL query for the RestAPI that matches the parameters passed in.

The latter f[] has overwritten the former. Therefore, only the second query is implemented on the query part of the URL for the Rest APIs.

**Comment by alexeyOnGitHub** [comment]
I added this implementation: https://github.com/taskadapter/redmine-java-api/commit/69723c4463f41bec077d9282cb3903c17100b31c

cannot create any reasonable integration test because there is no documentation on Redmine free-form search anywhere. the test I came up with (not committed this) returns more than 1 issue, which indicates that search terms use "or" rather than "and".
```

    /**
     * regression test for https://github.com/taskadapter/redmine-java-api/issues/12 and
     * https://github.com/taskadapter/redmine-java-api/issues/215
     */
    @Test
    public void issuesCanBeFoundByMultiQuerySearch() throws RedmineException {
        final Issue issue1 = IssueFactory.create(projectId, "summary 1 here");
        issue1.setDescription("abc description");
        issueManager.createIssue(issue1);

        final Issue issue2 = IssueFactory.create(projectId, "summary 2 here");
        issue2.setDescription("def totally different description");
        issueManager.createIssue(issue2);

        final Issue issue3 = IssueFactory.create(projectId, "another");
        issue3.setDescription("abc");
        issueManager.createIssue(issue3);

        Params params = new Params()
                .add("set_filter", "1")
                .add("f[]", "summary")
                .add("op[summary]", "~")
                .add("v[summary]", "another")
                .add("f[]", "description")
                .add("op[description]", "~")
                .add("v[description][]", "abc");

        final ResultsWrapper<Issue> list = issueManager.getIssues(params);
        // only 1 issue must be found
        assertThat(list.getResults()).hasSize(1);
    }

```
would anyone care to provide a set of search params that would make sense for this test?

**Comment by tza** [comment]
Thank you, this Params implementation looks okay and will help avoiding the "duplicate" parameter key problem.

One point for the test above and the javadoc of Params: 'summary' was a name of my implementation to query the subject parameter, the REST API uses and needs 'subject'.
So the correct code and javadoc should be something like
```
  .add("f[]", "subject")
  .add("op[subject]", "~")
  .add("v[subject]", "another")
```

For testing the REST API and check the results, I prefer calling the Redmine REST API directly via URL and here is what i found out for your OR/AND problem. 
Basicly as short summary, I see the problem more in the Redmine REST API... as long the taskadapter API supports multiple duplicate keys via Params, the taskadaper API should be fine! 

So, using the Redmine demo page:

(1) Query all tickets of an specific author:
http://demo.redmine.org/issues.xml?author_id=166251 (works)

(2) Query all tickets with subject test:
http://demo.redmine.org/issues.xml?f[]=subject&op[subject]=~&v[subject][]=test (works)

(3) Try to combine (1) and (2), but the result is same as (2) ... without author filtering:
(not working!) http://demo.redmine.org/issues.xml?f[]=subject&op[subject]=~&v[subject][]=test&author_id=166251 (not working!) 

(4) Try to combine (1) and (2) with f[],op[] and v[]:
http://demo.redmine.org/issues.xml?f[]=subject&op[subject]=~&v[subject][]=test&f[]=author_id&op[author_id]=~&v[author_id][]=166251 (works)

Since the REST API is not document well, I cannot say why author can be queried by ID with (1), but it is not working in combination with (2). 

Calling the URL (4) shows, that the combination of several f[], v[] and op[] params should work.
I think Szenario (4) can be used for the Unit test.

**Comment by alexeyOnGitHub** [comment]
thank you, @tza . I added "author_id" to the query. here is the new test: https://github.com/taskadapter/redmine-java-api/commit/c4d3b97929d8872f22a426e01e932e935612c7ea
