### ISSUE TITLE
support nonProxyHosts setting

### ISSUE THREAD

**Issue by uolter** [taskadapter/redmine-java-api#182]
It looks like that it's not possible to configure http.nonProxyHosts parameter.

In the RedmineManagerFactory class only http.proxyHost and http.proxyPort are considered.

**Comment by alexeyOnGitHub** [comment]
do you have a fix for this issue?

**Comment by uolter** [comment]
Hello Alexey.
I put something here but not tested enough. I am not fluent in java:
https://github.com/uolter/redmine-java-api

**Comment by alexeyOnGitHub** [comment]
RedmineManagerFactory  has createDefaultHttpClient() method that allows you to provide a pre-configured Apache HttpClient instance with nonProxyHosts and whatever other settings you need.

it would be nice to support nonProxyHosts for default Http Client created in this class RedmineManagerFactory   if none is provided, but since nobody is willing to dig into this and submit a functional PR, I'm going to close this.

this is largely out of scope of this library.
