### ISSUE TITLE
Solution for #114 breaks existing code

### ISSUE THREAD

**Issue by matthiasblaesing** [taskadapter/redmine-java-api#196]
If I'm not mistaken, the solution for issue #114 breaks my code.

Did I get this discussion correctly, that instead of adding a method with the new behavior the current behavior was modified to not handle paging anymore?

There is an example here:

https://github.com/redminenb/redminenb/blob/master/dev/src/main/java/com/kenai/redminenb/query/RedmineQuery.java#L298

Before that line I build the filter list from the user input and the fetch the issues. I expected to get all issues.

While I see adding paging ability as a good extension, I don't see a reason to break the existing behavior.

I also would not return a plain list, if the ResultWrapper was validly introduced to hold totalResult count.

**Comment by alexeyOnGitHub** [comment]
we went back and forth and decided that having better (less misleading) API is more important than maintaining backward compatibility in this case.
getIssues() is the lowest-level method which accepts any Http parameters you provide. overriding or adding some magical parameters in it would be surprising to callers.
it was essentially a design error which we fixed in #114.
there are many other methods in IssueManager that handle paging for callers. 
now clients are free to use either low-level method where they handle paging themselves or higher-level methods that do that for them.

**Comment by matthiasblaesing** [comment]
Thank you for summarizing your reasoning. I would suggest, that you bump version to 3.0.0 in this case. I normally expect an API to be stable inside a major version, as your change did not change the signature, but introduced radically different behavior.

**Comment by alexeyOnGitHub** [comment]
right. let's see how many other changes we'll have before the next release...
