### ISSUE TITLE
Issue start date is reset during partial issue update

### ISSUE THREAD

**Issue by keritaf** [taskadapter/redmine-java-api#203]
I try to update issue like that:
```java
Issue issue = IssueFactory.create(1234);
issue.setNotes("test note");
issueManager.update(issue);
```
After the update journal is created, but issue start date is set to none.

As I see, the problem is [here](https://github.com/taskadapter/redmine-java-api/blob/71ae4aa9feaf39afa6e799fcac8c5e7b1ae07134/src/main/java/com/taskadapter/redmineapi/internal/RedmineJSONBuilder.java#L311-L312). ```due_date``` field is nullable, but ```start_date``` is not - which leads to it being sent every time. It seems that ```start_date``` is not a required field for an issue - could we make it behave the same way as ```due_date```?

**Comment by alexeyOnGitHub** [comment]
task #61 should address many partial update issues. feel free to try this https://github.com/taskadapter/redmine-java-api/tree/ask-61-save-nulls-if-set branch. it's a work in progress, but having early feedback is always great.

**Comment by alexeyOnGitHub** [comment]
I added 3.0.0 milestone tag to this task because it will be addressed along with all other partial updates in  this branch: https://github.com/taskadapter/redmine-java-api/tree/ask-61-save-nulls-if-set 

if you can review and play around with the code in that branch and give early feedback, that would be very helpful.

**Comment by alexeyOnGitHub** [comment]
the change was merged to "master".
