### ISSUE TITLE
Content-Length not set when creating an attachment

### ISSUE THREAD

**Issue by wiax** [taskadapter/redmine-java-api#233]
Transport.upload doesn't set the Content-Length on the HTTP request. As result, Redmine server complains about the missing HTTP header named as Content-Length.

**Comment by PMitrafanau** [comment]
Encountered this problem too... It caused by `InputStreamEntity` which is used inside `Transport.upload` method. Since the code passes `-1` as the `contentLength`, `InputStreamEntity` uses chunked upload which seems not to be supported by Redmine REST API. **The problem prevents to upload any attachments.**

I have done the following experiments:
- Explicitly specified `contentLength`. Upload was successful;
- Previous clause + set `chunked` to `true`. Upload was unsuccessful

**Comment by PMitrafanau** [comment]
Library uses chunked transfer encoding (you can see `InputStreamEntity` with content length set to `-1`), so most probably your server is not configured to support it. I used docker container providing Redmine which used WEBrick and had problems too.

**Comment by alexeyOnGitHub** [comment]
this is a duplicate of #78
