### ISSUE TITLE
Issue.getClosedOn() returns null for a closed ticket

### ISSUE THREAD

**Issue by tmert1012** [taskadapter/redmine-java-api#291]
I have an issue that is closed in redmine and calling getClosedOn() always returns null.

I think a workaround may be getting the last journal created date of when status was updated to closed.

**Comment by alexeyOnGitHub** [comment]
can you please check/debug what REST API returns (raw json) when you close an issue? maybe it is a parsing issue. but more likely is that Redmine returns null indeed, in which case this is a bug on the server and should be fixed in Redmine. here is their bug tracker: http://www.redmine.org/projects/redmine/issues
feel free to check with Redmine developers.

is a consumer of this API wants to decide that "close date" and "last journal created date" are equivalent, this is up the them, this should not be hardcoded into the library itself. the goal of the library is to provide access to Redmine REST API. defining use-case-specific rules is out of scope.

**Comment by alexeyOnGitHub** [comment]
no response - closing
